[SPARK-270116] Add RenderConfig for Input Elements (Windows)
AdaptiveCards-Desktop/AdaptiveCards pull request #218
Opened 2021-09-27 11:48 UTC by dgharde

## Related Issue
Please use one of the well-known [github fixes keywords](https://help.github.com/en/articles/closing-issues-using-keywords) to reference
the issues fixed with this PR (eg Fixes #<github issue number>). If an issue doesn't yet exist please create one if reasonable to aid 
in issue tracking.

**NOTE**: For multiple issues resolved by this PR use the corresponding keywords **every time** in a comma-delimited list per the reference
page above.

## Description

Add a new RenderConfig class which can be used for all elements

## Sample Card
If appropriate, please include a link to a card in one of the samples directories that can be used to validate this change. This can be an existing card or a card added with this PR.

## How Verified
How you verified the fix, including one or all of the following: 
1. New unit tests that were added if any. If none were added please add a quick line explaining why not.
2. Existing relevant unit/regression tests that you ran
3. Manual scenario verification if any; ***Do include .gif's or screenshots of the testing you performed here if you think that it 
will aid in code reviews or corresponding fixes on other platforms for eg.***

2021-09-27 11:53 UTC, ggovardh approved these changes

2021-09-28 10:43 UTC, rj100189 requested changes
To be updated as per discussion.

2021-10-05 11:32 UTC, rj100189 commented on source/qml/Library/RendererQml/AdaptiveCardRenderConfig.h
> +        const bool isDarkMode();
```suggestion
        bool isDarkMode() const;
```

2021-10-05 11:32 UTC, rj100189 commented on source/qml/Library/RendererQml/AdaptiveCardRenderConfig.cpp
> +    AdaptiveCardRenderConfig::AdaptiveCardRenderConfig(bool isDarkMode)
```suggestion
    AdaptiveCardRenderConfig::AdaptiveCardRenderConfig(bool isDarkMode)
    : isDark(isDarkMode)
```

2021-10-05 11:32 UTC, rj100189 commented on source/qml/Library/RendererQml/AdaptiveCardRenderConfig.h
> +        InputTextConfig getInputTextConfig();
```suggestion
        InputTextConfig getInputTextConfig() const;
```

2021-10-05 11:32 UTC, rj100189 commented on source/qml/Library/RendererQml/AdaptiveCardRenderConfig.h
> +        InputTextConfig textInputConfig;
```suggestion
        bool m_isDark;
        InputTextConfig m_textInputConfig;
```

2021-10-05 11:41 UTC, rj100189 approved these changes

2021-10-05 11:42 UTC, merged